name: build
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn install --frozen-lockfile
      - run: yarn format:check
      - run: yarn lint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          tags: nihalgonsalves/next-typescript-eslint-template:latest
          load: true
      - name: Run image and make request
        run: |
          docker run --rm --name test -d -p 127.0.0.1:3000:3000 nihalgonsalves/next-typescript-eslint-template
          # easier than implementing retry logic for this simple check
          sleep 3
          curl http://localhost:3000/
          docker stop test
